services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: salsa
      POSTGRES_PASSWORD: salsa
      POSTGRES_DB: salsa_rayo
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
